development:
  clients:
    default:
      database: gateway_web_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: gateway_web_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: gateway_web_production
      hosts:
        - localhost:27017
      options:
  options:
